---
title: Hi, again.
author: Monica Gerber
date: '2020-03-30'
slug: hi-again
categories: []
tags:
  - coivd-19
---

Well, I failed miserably at writing a new post every week. However, I actually did pretty great biking throughout the winter. I biked to work _every day_ except the week that I got sick with a nasty stomach bug.  Even through the Seattle rain -- it wasn't that bad! Here we are on the other side of daylight savings time, it's officially spring and the days are getting longer, and suddenly everything that is familiar is changing around us as we, first, try to flatten the curve, and then to adapt to a post-COVID-19 world. Writing about biking feels even more important to me. Even though I'm not a bike commuter at the moment, it's one of the few outside activities that I can still enjoy close to my home. Many cars are off the streets in Seattle, which makes it easier to imagine a world where biking is a safe option. Plus, writing about biking will be a constructive distraction from constantly scanning my Twitter feed for the latest COVID-19 news. And now I official sign on again to my challenge of weekly blogging.
